# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: set up mongodb
      uses: supercharge/mongodb-github-action@1.4.1
      with:
        mongodb-version: 4.4
    - name: install requirements
      run: pip install -r requirements.txt
    - name: run pytest
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        NAVER_LOGIN_CLIENT_ID: ${{ secrets.NAVER_LOGIN_CLIENT_ID }}
        NAVER_LOGIN_CLIENT_SECRET: ${{ secrets.NAVER_LOGIN_CLIENT_SECRET }}
        NAVER_LOGIN_SERVICE_URL: ""
        NAVER_LOGIN_CALLBACK_URL: ""
        MONGODB_HOST: "mongodb://localhost:27017"
        KAKAO_REST_API: ${{ secrets.KAKAO_REST_API }}
      run: pytest
