# This is a basic workflow to help you get started with Actions

name: Scraper

# Controls when the action will run.
# 참고: https://crontab.guru/examples.html
on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.4.1
        with:
          mongodb-version: 4.4
      - name: install requirements
        run: |
          pip install -r requirements.txt
      - name: run scraper
        env:
          MONGODB_HOST: "mongodb://localhost:27017"
          REST_API: ${{ secrets.REST_API }}
        run: |
          cd app/views
          python scraper.py